apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv1 
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
     path: "/mnt/data"
     type: "DirectoryOrCreate"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pstgres-pvc
  namespace: nodejs-ns 
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  
